name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t aliceychang/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true aliceychang/react-redis-postgres npm test
      - run: docker build -t aliceychang/multi-client ./client
      - run: docker build -t aliceychang/multi-nginx ./nginx
      - run: docker build -t aliceychang/multi-server ./server
      - run: docker build -t aliceychang/multi-worker ./worker
      - run: docker push -t aliceychang/multi-client
      - run: docker push -t aliceychang/multi-nginx
      - run: docker push -t aliceychang/multi-server
      - run: docker push -t aliceychang/multi-worker